### PR TITLE
Fixed Linux Authentication Issue using PSCore 7.0.0+ on Linux

### LINKED ISSUE #5: Authentication on Linux using PSCore 7.0.0+ is broken
- Version of PowerShell you're using
PowerShell Core 7.0.0
- PowerShell host you're using (eg. Console Host, ISE, Visual Studio)
Console Host
- Operating system you're running
WSL
- Version of Jenkins PowerShell Module you're using (use `Get-Module -Name Jenkins`)
1.0.3.257

Running the Jenkins Module on WSL or Linux using PowerShell 7.0.0+ causes an authentication error similar to the below:

```
Error 401 Invalid password/token for user:***********  HTTP ERROR 401 Invalid password/token for user:*********** 
     | URI:/job/terraform-clients/createItem STATUS:401 MESSAGE:Invalid password/token for user:***********
```

This is due to the method the password is decrypted being broken and not advised ([See here](https://github.com/PowerShell/PowerShell/issues/12114)).

Suggest we move to using something like this instead which will fix the Module for Linux:
`$Password = $Credential.GetNetworkCredential().Password`

### PR DESCRIPTION
**Pull request by matthorgan**
# Pull Request

## Bug Fixes

This will fix the flawed method for decrypting the Jenkins password which is broken using PSCore 7.0.0+ on Linux. Discussion around this can be found [here](https://github.com/PowerShell/PowerShell/issues/12114)

- Fixes #5 

@PlagueHO let me know if there's anything I've missed 😃

---
This change is [Reviewable](https://reviewable.io/reviews/plagueho/jenkins/6)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @matthorgan - thank you for submitting this. I'll review this weekend. Looks like the MacOS build is failing, but this is because Travis CI agent has changed so I'll need to fix this separately. I'm planning to move the build over to Azure DevOps at some point anyway.

**Comment by adamrushuk** [comment]
@matthorgan I've just noticed the OSX image is _very_ old, hence long updates.
Try changing 
https://github.com/PlagueHO/jenkins/blob/dev/.travis.yml#L6 to `osx_image: xcode12u`

**Comment by matthorgan** [comment]
> Hi @matthorgan - thank you for submitting this. I'll review this weekend. Looks like the MacOS build is failing, but this is because Travis CI agent has changed so I'll need to fix this separately. I'm planning to move the build over to Azure DevOps at some point anyway.

Apologies @PlagueHO , thought I'd have a crack at fixing the Travis CI bits by bumping the image and trying the homebrew addon but to no avail. Azure DevOps would be good 😃

**Comment by adamrushuk** [comment]
Hacktoberfest starts in a few weeks, so I may try and fix the test pipeline and submit a PR.

**Comment by PlagueHO** [comment]
Sweet @adamrushuk - I'm planning on migrating the module over to use Sampler (a build framework) with Azure DevOps (unifying from AppVeyor & Travis) - like the pipeline in this Module: https://github.com/PlagueHO/CosmosDB. Feel free to take a look at that to see an indication in the planned changes.

**Comment by adamrushuk** [comment]
> Sampler (a build framework)

CosmosDB and https://github.com/gaelcolas/Sampler both look awesome. You and Gael produce excellent projects, so thanks for the hard work!

**Comment by PlagueHO** [comment]
Thanks @adamrushuk - Sampler is all down to Gael :grin: But keen to upgrade this to Sampler - if you're keen I'll add an issue and assign it to you. It should be reasonably straight forward if you copy files from https://github.com/PlagueHO/LoopbackAdapter - which is another repo I upgraded to Sampler recently.

**Review by PlagueHO — CHANGES_REQUESTED** [review]
@matthorgan , I think as it is too much of a pain to fix Travis and we're going to replace it anyway, I'll just merge this with the failing tests. Can you add the entry to README.md about dropping support for older PS versions and I'll merge?

Can you also add an entry to the CHANGELOG.md # Unreleased section mentioning this change?

> Reviewed 2 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/plagueho/jenkins/6#-:-MIIdtsnDkKAMb_QzFj2:b6o8mp)* status: all files reviewed, 1 unresolved discussion (waiting on @matthorgan)

___
*[src/lib/Get-JenkinsCrumb.ps1, line 29 at r3](https://reviewable.io/reviews/plagueho/jenkins/6#-MIIcBPPDpll_diDbAKi:-MIIcBPQEv7uQFloBwFz:b2c0ywk) ([raw file](https://github.com/plagueho/jenkins/blob/31d61112d36048c35ffce6de82701c4293695031/src/lib/Get-JenkinsCrumb.ps1#L29)):*
> ```PowerShell
> 
>         # Decrypt the secure string password
>         $Password = $Credential.GetNetworkCredential().Password
> ```

The reason for the old code is to support older versions of PS where .GetNetworkCredential().Password didn't work. Perhaps we consider dropping support for anything below PS 5? Can you add an entry to https://github.com/PlagueHO/jenkins/blob/dev/README.md#compatibility-and-testing saying that PowerShell 5.0 and below is no longer supported?

**Comment by adamrushuk** [comment]
> Thanks @adamrushuk - Sampler is all down to Gael 😁 But keen to upgrade this to Sampler - if you're keen I'll add an issue and assign it to you. It should be reasonably straight forward if you copy files from https://github.com/PlagueHO/LoopbackAdapter - which is another repo I upgraded to Sampler recently.

I'll leave Sampler to you, as have too much on atm.

**Review by PlagueHO — COMMENTED** [review]
No worries! I'm going to try and get it done tonight...

> *[Reviewable](https://reviewable.io/reviews/plagueho/jenkins/6#-:-MIkl11W5sXNSC_O6SCD:b2927gu)* status: all files reviewed, 1 unresolved discussion (waiting on @matthorgan)

**Comment by PlagueHO** [comment]
FYI, I'm adding this fix into the conversion to Azure DevOps because otherwise the tests on PS7 fail.

**Comment by PlagueHO** [comment]
This PR has been superceeded by #10

**Comment by matthorgan** [comment]
> FYI, I'm adding this fix into the conversion to Azure DevOps because otherwise the tests on PS7 fail.

Ah apologies I didn't get round to doing this in time. Good job on the Continuous Delivery fixes though! 🥇

**Pull request closed without merging**
