### PR TITLE
New-JenkinsApiToken

### PR DESCRIPTION
**Pull request by HaxtonFale**
# Pull Request

## Improvements / Enhancements

- Implemented New-JenkinsApiToken, as per #8 by @PlagueHO

- - -
This change is [Reviewable](https://reviewable.io/reviews/PlagueHO/jenkins/23)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Looks like I'll need to update the CICD pipeline to get the builds working again. I'll work on this over the weekend. Shouldn't take long.

**Comment by PlagueHO** [comment]
@HaxtonFale - can you rebase onto main so that the CI pipeline starts working again?

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/PlagueHO/jenkins/23)* status: all files reviewed, 1 unresolved discussion (waiting on @HaxtonFale)

___
*[`docs/New-JenkinsApiToken.md` line 17 at r1](https://reviewable.io/reviews/PlagueHO/jenkins/23#-NeuWwhe69l8_fjUMJ1P:-NeuWwhe69l8_fjUMJ1Q:bqap9gv) ([raw file](https://github.com/PlagueHO/jenkins/blob/55853d066f7636312731f67b37712a89bea4e6eb/docs/New-JenkinsApiToken.md#L17)):*
> ```Markdown
> 
> ```powershell
> New-JenkinsFolder [-Uri] <String> [[-Credential] <PSCredential>] [[-Crumb] <String>]
> ```

This should be: New-JenkinsApiToken

**Comment by HaxtonFale** [comment]
> > Reviewed 6 of 6 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/PlagueHO/jenkins/23)_ status: all files reviewed, 1 unresolved discussion (waiting on @HaxtonFale)
> 
> _[`docs/New-JenkinsApiToken.md` line 17 at r1](https://reviewable.io/reviews/PlagueHO/jenkins/23#-NeuWwhe69l8_fjUMJ1P:-NeuWwhe69l8_fjUMJ1Q:bqap9gv) ([raw file](https://github.com/PlagueHO/jenkins/blob/55853d066f7636312731f67b37712a89bea4e6eb/docs/New-JenkinsApiToken.md#L17)):_
> 
> > ```
> > ```powershell
> > New-JenkinsFolder [-Uri] <String> [[-Credential] <PSCredential>] [[-Crumb] <String>]
> > ```
> 
> This should be: New-JenkinsApiToken

Fixed.

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/PlagueHO/jenkins/23#-:-NfSOo087nwJAnVNm7Vn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @HaxtonFale)

**Pull request merged**
